### ISSUE TITLE
trying to reverse-step a recording of QEMU asserts: FATAL /home/petmay01/src/rr/src/ReplaySession.cc:315:cont_syscall_boundary() errno: 0 'Success'

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1481]
I have a recording of QEMU which will replay forwards fine. However attempting a reverse-step causes an rr assertion:

```
e104462:trusty:qemu$ ~/src/rr-obj64/bin/rr replay ~/.rr/qemu-system-arm-6
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/petmay01/linaro/qemu-from-laptop/qemu/build/a64-targets-nodbg/arm-softmmu/qemu-system-arm...done.
Really redefine built-in command "checkpoint"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "checkpoint"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
/proc/28299/fd/4:53: Error in sourced command file:
Undefined maintenance set command: "target-async 0".  Try "help maintenance set".
Remote debugging using 127.0.0.1:28300
warning: limiting remote suggested packet size (206696 bytes) to 16384
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.19.so...done.
done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
0x00002aaaaaaafa86 in _dl_start (arg=0x7fffffffe330) at rtld.c:380
380     rtld.c: No such file or directory.
(gdb) handle SIGUSR1 pass noprint nostop
Signal        Stop      Print   Pass to program Description
SIGUSR1       No        No      Yes             User defined signal 1
(gdb) break spitz_out_switch
Breakpoint 1 at 0x5555556b8490: file /home/petmay01/linaro/qemu-from-laptop/qemu/hw/arm/spitz.c, line 774.
(gdb) c
Continuing.
audio: Could not init `oss' audio driver
[New Thread 28035.28037]
[Switching to Thread 28035.28037]

Breakpoint 1, spitz_out_switch (opaque=0x5555563664b0, line=0, level=1)
    at /home/petmay01/linaro/qemu-from-laptop/qemu/hw/arm/spitz.c:774
774     {
(gdb) rs
[FATAL /home/petmay01/src/rr/src/ReplaySession.cc:315:cont_syscall_boundary() errno: 0 'Success'] 
 (task 28324 (rec:28037) at time 6373)
 ->  Assertion `false' failed to hold. Replay got unrecorded signal 11
Launch gdb with
  gdb /home/petmay01/linaro/qemu-from-laptop/qemu/build/a64-targets-nodbg/arm-softmmu/qemu-system-arm
and attach to the rr debug server with:
  target remote :28324
```

This is with rr built from git commit 89e53a6176a058270a2fde91c894edb740ce3a4c.

Reverse-step in a simple hello-world app seems to work OK, so it must be something specific to what QEMU is doing.

Dump of the event log around time 6373 in case that is helpful:

```
  global_time:6371, event:`SYSCALL: ppoll' (state:ENTERING_SYSCALL) tid:28035, ticks:43500534
 rax:0xffffffffffffffda rbx:0x55555634fa00 rcx:0xffffffffffffffff rdx:0x7fffffffdf60 rsi:0x5 rdi:0x5555569cea70 rbp:0x7fffffffdfb4 rsp:0x7fffffffdf40 r8:0x8 r9:0x0 r10:0x0 r11:0x293 r12:0x17ce62c r13:0xf r14:0x0 r15:0x555556331b30 rip:0x2aaab26181ef eflags:0x293 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10f}
{
  global_time:6372, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:28037, ticks:20375577966
 rax:0x0 rbx:0x55555637bbb0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x80 rdi:0x555555e9e100 rbp:0x555555e9a860 rsp:0x2aaac37e08f8 r8:0x555555e9e100 r9:0xb r10:0x0 r11:0x246 r12:0x555555e451a8 r13:0x555555dda2e0 r14:0x555556373960 r15:0x80000000 rip:0x2aaab231bf2c eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca}
{
  global_time:6373, event:`SYSCALL: clock_gettime' (state:ENTERING_SYSCALL) tid:28037, ticks:20375583681
 rax:0xffffffffffffffda rbx:0xfffffffffffffe50 rcx:0xffffffffffffffff rdx:0xffffffffffd047b0 rsi:0x2aaac37e01c0 rdi:0x1 rbp:0x0 rsp:0x2aaac37e0078 r8:0x1 r9:0xffffffff r10:0x55555637cbb0 r11:0x216 r12:0x2aaac37e01c0 r13:0x1 r14:0x4 r15:0x2aaac37e0168 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe4}
{
  global_time:6374, event:`SYSCALL: clock_gettime' (state:EXITING_SYSCALL) tid:28037, ticks:20375583681
 rax:0x0 rbx:0xfffffffffffffe50 rcx:0xffffffffffffffff rdx:0xffffffffffd047b0 rsi:0x2aaac37e01c0 rdi:0x1 rbp:0x0 rsp:0x2aaac37e0078 r8:0x1 r9:0xffffffff r10:0x55555637cbb0 r11:0x216 r12:0x2aaac37e01c0 r13:0x1 r14:0x4 r15:0x2aaac37e0168 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe4}
{
  global_time:6375, event:`SYSCALL: clock_gettime' (state:ENTERING_SYSCALL) tid:28037, ticks:20375584796
 rax:0xffffffffffffffda rbx:0xfffffffffffffe50 rcx:0xffffffffffffffff rdx:0xffffffffffd047b0 rsi:0x2aaac37e01c0 rdi:0x1 rbp:0x0 rsp:0x2aaac37e0078 r8:0x1 r9:0xffffffff r10:0x5555556566b0 r11:0x216 r12:0x2aaac37e01c0 r13:0x1 r14:0x4 r15:0x2aaac37e0168 rip:0x70000018 eflags:0x216 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe4}
```

**Comment by pm215** [comment]
Further investigation suggests that the QEMU process has somehow lost one of its mmap'd areas. The segfault happens inside memcpy(), with the offending address being in this mapping (as per /proc/<pid>/maps):
2aaac3e00000-2aaac7e40000 rw-p 00000000 00:00 0 
and which works before we do the reverse step:
(gdb) print /x *(uint32_t*)0x2aaac3e0700c
$3 = 0xa030040e

I'm a bit confused about which of the various processes and tasks with the qemu command line under the rr process are doing what, but at least the one which the rr emergency debugger is trying to talk to is simply missing this mapping from its /proc/<pid>/maps, so the emergency-debugger also thinks the address isn't readable.

**Comment by pm215** [comment]
The mappings which "get lost" seem to be exactly those which QEMU creates with its qemu_anon_ram_alloc() function (which mmap()s a big area and then chops off the head and tail with munmap()). I'm wondering if AddressSpace.cc is mishandling this somehow. Unfortunately the debug log doesn't seem to give a complete picture of what AddressSpace.cc thinks the current mapping is, and I can't reproduce with a simple test case. But if I do a replay of QEMU with the -K flag to check mmap mappings then it asserts in simple replay:
```
[FATAL /home/petmay01/src/rr/src/AddressSpace.cc:933:assert_segments_match() errno: 0 'Success'] 
 (task 6772 (rec:17396) at time 202)
 ->  Assertion `same_mapping' failed to hold. 
Cached mapping 0x7ffffffde000-0x7fffffffe000 0x3 f:0x2 should be 0x7ffffffde000-0x7ffffffff000 0x7 f:0x2
```
(though oddly the mapping being complained about there is the stack, so maybe our aligned-mmap function is a red herring.)

If you have any suggestions for further debugging/investigation I'm happy to have a go.

**Comment by pm215** [comment]
The -K assert appears to be because:
[AddressSpace] mprotect(0x7fffffffe000, 4096, 0x1000007)
[AddressSpace]   protecting (0x7fffffffe000-0x7ffffffff000 0 f:0) ...
[AddressSpace]   erased (0x7ffffffde000-0x7ffffffff000 0x3 f:0x2)

the guest did an mprotect(..., PROT_GROWSDOWN), which is asking for the change to extend to the start of a grows-down VMA, but we only applied the change to the specified region.

**Comment by pm215** [comment]
That pull request addresses the lack of PROT_GROWSDOWN support (though you should check it carefully before merging because I'm kind of blundering about as a non-native-speaker of C++ :-)). 

However the replay then falls over later on with a different mismatch:
```
[FATAL /home/petmay01/src/rr/src/AddressSpace.cc:947:assert_segments_match() errno: 0 'Success'] 
 (task 21845 (rec:17396) at time 2844)
 ->  Assertion `same_mapping' failed to hold. 
Cached mapping 0x55555600c000-0x55555668e000 0x3 f:0x2 should be 0x55555600c000-0x55555668d000 0x3 f:0x2
```
A quick look at the log suggests this is mishandling of brk() moving the program break down in memory: previously we did
```
[AddressSpace] brk(0x55555668e000)
```
and passed the consistency checks with
```
[AddressSpace] examining /proc/maps segment 0x55555600c000-0x55555668e000 0x3 f:0x2
```
but then
```
[AddressSpace] brk(0x55555668d000)
[AddressSpace] mmap(0x5555564a2000, 2011136, 0x3, 0x22, 0
[AddressSpace] munmap(0x5555564a2000, 2011136)
[AddressSpace]   unmapping (0x5555564a2000-0x55555668d000 0 f:0) ...
[AddressSpace]   erased (0x5555564a2000-0x55555668e000 0x3 f:0x22) ...
[AddressSpace]   mapping 0x5555564a2000-0x55555668d000 0x3 f:0x22
[AddressSpace]     (flags or prot differ)
[AddressSpace]     adjacent!
[AddressSpace]     (not adjacent in memory)
[AddressSpace]   coalescing 0x5555564a2000-0x55555668e000 0x3 f:0x22
```
and then we fail the consistency check because the kernel has truncated the mapping to the new program break but our cached version is still at the old location.

**Comment by rocallahan** [comment]
Thanks for digging into this!

I'd never heard of PROT_GROWSDOWN before. It's not in any `mprotect` man page I can find...

**Comment by rocallahan** [comment]
I'm awfully tempted to rewrite our AddressSpace code to avoid all these problems by re-reading /proc/maps after mmap/brk syscalls, but I guess the right thing to do at the moment is to write testcases for these issues and patch them. I'd like to release 4.0 soon and rewriting address-space tracking should happen after that.

**Comment by rocallahan** [comment]
OK, I've merged your PR (with some changes) and I've also merged a fix for `brk()` shrinking the heap. Please try again :-)

**Comment by pm215** [comment]
Those changes let me do a complete replay with -K (well, with a modified variant of -K that only does the consistency check every billion ticks, because otherwise it spent all its time checking and didn't make any progress). However the original reverse-step assert still happens...

**Comment by rocallahan** [comment]
If you follow the steps to attach to the rr debug server, and get a stack trace, can you get some idea of what causes the unexpected SIGSEGV?

BTW I'm curious why your rr dump shows `clock_gettime` syscalls . They should have been optimized via syscall buffering and appear under `SYSCALLBUF_FLUSH` instead of as regular syscalls as in your dump. If they show up as regular syscalls all the time there's probably some major performance improvements left on the table. Anyway that'll be a separate issue.

**Comment by pm215** [comment]
The SIGSEGV is in a memcpy() (see comment 2 in this bug) -- the memory that should be present (and was present in the forwards run) is just missing.

**Comment by pm215** [comment]
If I try using the "run <timestamp>" rather than reverse-step, then behaviour seems to depend on where I try to resume the run from. 'when' reports that my breakpoint in spitz_switch() is hit at timestamp 147685. If I say "run 50000" that works ok (executing until it hits the bp again). "run 100000" hits the same assert as a reverse-step.

**Comment by pm215** [comment]
I added this to the end of Task::clone():
```
+  LOG(error) << "firing mmap check at end of clone";
+  if (t->session().can_validate()) {
+    t->vm()->verify(t);
+  }
```
and then partway through a replay run it fires:
```
Cached mapping 0x2aaac3e00000-0x2aaac7e40000 0x3 f:0x2 should be 0x2aaac7e65000-0x2aaac8ee6000 0x3 f:0x2
```
because proc/maps has
```
2aaac3ac4000-2aaac3bc4000 rw-s 00000000 08:05 5767401                    /tmp/rr-tracee-shmem-2039-1 (deleted)
2aaac3bc4000-2aaac3cc4000 rw-s 00000000 08:05 5767439                    /tmp/rr-tracee-shmem-2040-2 (deleted)
2aaac3cc4000-2aaac3df1000 rw-p 00000000 00:00 0 
2aaac7e65000-2aaac8ee6000 rw-p 00000000 00:00 0 
2aaac8f30000-2aaac8f55000 rw-p 00000000 00:00 0 
```
where the cache has
```
0x2aaac3ac4000-0x2aaac3bc4000 rw-s 00000000 08:05 5767401    /tmp/rr-tracee-shmem-2039-1 
0x2aaac3bc4000-0x2aaac3cc4000 rw-s 00000000 08:05 5767439    /tmp/rr-tracee-shmem-2040-2 
0x2aaac3cc4000-0x2aaac3df1000 rw-p 00000000 00:00 0           
0x2aaac3e00000-0x2aaac7e40000 rw-p 00000000 00:00 0           
0x2aaac7e65000-0x2aaac8ee6000 rw-p 00000000 00:00 0           
0x2aaac8f30000-0x2aaac8f55000 rw-p 00000000 00:00 0           
```
so the cache is correct and /proc/maps is wrong (assuming that I've not put the verify call somewhere invalid, but /proc/maps not being correct would match the symptoms).

**Comment by pm215** [comment]
Aha. QEMU is calling "madvise(..., MADV_DONTFORK)" for this memory, which tells the kernel not to copy it across to the child on fork(). If rr needs the copying semantics it's going to have to filter out that madvise call...

**Comment by pm215** [comment]
(For the curious, this QEMU commit has the rationale for why we're doing weird things with DONTFORK in the first place: http://git.qemu.org/?p=qemu.git;a=commitdiff;h=3e469dbfe413c25d48321c3a19ddfae0727dc6e5)

**Comment by rocallahan** [comment]
Aha, OK! I should be able to fix that.

**Comment by rocallahan** [comment]
I guess the `madvise` man page text "This call does not influence the semantics of the application (except in the case of MADV_DONTNEED), but may influence its performance." is incorrect after all...

**Comment by rocallahan** [comment]
OK, I pushed a fix for MADV_DONTFORK.

**Comment by cgjones** [comment]
```
/home/travis/build/mozilla/rr/src/record_syscall.cc: In function ‘Switchable rec_prepare_syscall_arch(Task*, TaskSyscallState&)’:
/home/travis/build/mozilla/rr/src/record_syscall.cc:2440:14: error: ‘MADV_DONTDUMP’ was not declared in this scope
/home/travis/build/mozilla/rr/src/record_syscall.cc:2441:14: error: ‘MADV_DODUMP’ was not declared in this scope
make[2]: *** [CMakeFiles/rr.dir/src/record_syscall.cc.o] Error 1
```

**Comment by rocallahan** [comment]
pushed a fix for that.

**Comment by khuey** [comment]
Can we use MADV_DONTFORK to fix the FIXME at post_fork_child?

**Comment by rocallahan** [comment]
Yes, I think that would work.

**Comment by pm215** [comment]
To test those MADV_DONTFORK fixes do I need to re-record or should they work just with a recompiled rr replay ?

**Comment by rocallahan** [comment]
Yeah, you need to rerecord since all `madvise`s were unconditionally syscall-buffered before, but we need to ensure DONTFORK/DOFORK cause ptrace traps to rr.

Great!
