### ISSUE TITLE
A way to turn off Werror

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1718]
Turning on Werror is really nice for developers but can be really annoy for packagers especially if there's no way to turn it off since it's really sensitive to compiler versions. E.g. GCC 6.1 gives me the following warning on ArchLinux. I'm not sure why there's a warning here but I think in general it's better to be able to disable `Werror`.

```
In file included from /home/yuyichao/projects/contrib/rr/src/Event.h:13:0,
                 from /home/yuyichao/projects/contrib/rr/src/record_signal.h:8,
                 from /home/yuyichao/projects/contrib/rr/src/record_signal.cc:3:
/home/yuyichao/projects/contrib/rr/src/Registers.h: In instantiation of 'void rr::Registers::set_arg(T) [with int Index = 3; T = std::nullptr_t]':
/home/yuyichao/projects/contrib/rr/src/AutoRemoteSyscalls.h:227:30:   recursively required from 'void rr::AutoRemoteSyscalls::syscall_helper(int, rr::Registers&, T, Rest ...) [with int Index = 2; T = long unsigned int; Rest = {std::nullptr_t, long unsigned int}]'
/home/yuyichao/projects/contrib/rr/src/AutoRemoteSyscalls.h:227:30:   required from 'void rr::AutoRemoteSyscalls::syscall_helper(int, rr::Registers&, T, Rest ...) [with int Index = 1; T = int; Rest = {long unsigned int, std::nullptr_t, long unsigned int}]'
/home/yuyichao/projects/contrib/rr/src/AutoRemoteSyscalls.h:156:5:   required from 'long int rr::AutoRemoteSyscalls::infallible_syscall(int, Rest ...) [with Rest = {int, long unsigned int, std::nullptr_t, long unsigned int}]'
/home/yuyichao/projects/contrib/rr/src/record_signal.cc:54:67:   required from here
/home/yuyichao/projects/contrib/rr/src/Registers.h:248:51: warning: parameter 'value' set but not used [-Wunused-but-set-parameter]
   template <int Index, typename T> void set_arg(T value) {
                                                   ^~~~~
```

**Comment by rocallahan** [comment]
Good point. I moved it to only be enabled for debug builds: https://github.com/mozilla/rr/commit/21c30a52026c46e596615def46ee641d3b291bd8
I'm assuming that packagers will make release builds and developers are likely to make debug builds. Does that look OK?

**Comment by yuyichao** [comment]
Hmm I'm actually using debug build for packaging after getting compiler errors when building rr with optimization on (the error was about reference to static symbols not found/optimized out).

Maybe that's overly conservative so I'll try and see if Release build works...

**Comment by rocallahan** [comment]
I think we should fix any errors that prevent you from making a release build.

**Comment by yuyichao** [comment]
Thx. It seems that the error I saw before was fixed already and I don't need to unset `CFLAGS`/`CXXFLAGS` and use Debug build anymore =)

I personally usually prefer a dedicated option since there are cases that the compiler gives better warnings with optimizations on but that's of course up to you to decide which is the most useful. The current solution is good enough for me.

**Comment by rocallahan** [comment]
Adding effectively a third build configuration has the problem that it gets increasingly less likely developers will consistently use any given configuration, increasing the likelihood that some configuration will break for someone.

We will still get warnings for issues that depend on higher optimization levels, they just won't be fatal. If I was going to change anything more here I'd actually increase the optimization level for debug builds. Debugging with -O2 isn't too bad.
