### ISSUE TITLE
--disable-cpuid-features-(ext) not properly masking CPU features

### ISSUE THREAD

**Issue by loganwendholt** [mozilla/rr#2643]
I'm trying to figure out the proper CPUID mask bits to record on a Skylake processor and replay on a Broadwell, but I keep running into the following error:

```
[ERROR .../src/ExtraRegisters.cc:433:set_to_raw_data()] Unsupported CPU features found: got 0x203 (x87 SSE PKRU), supported: 0x7 (x87 SSE AVX); Consider using rr cpufeatures and rr record --disable-cpuid-features-(ext)
```

So, it looks like I need to disable the PKRU feature. However, this issue is persistent even when fully masking off all extended and xsave features with  `--disable-cpuid-features-ext 0xffffffff,0xffffffff,0xffffffff --disable-cpuid-features-xsave 0xffffffff`

As far as I can tell by looking at the [CPUID docs](https://www.felixcloutier.com/x86/cpuid), it looks like the relevant PKU bits should be in EAX=0x7, ECX=0x0, which I have fully masked off with the above flags. So I can't figure out why this PKRU feature is still sticking around.

I also see some references to PKRU in EAX=0xD, ECX=0x0, so maybe the ability to mask this off needs to be added as an option in the command line arguments? But I also see AVX references in there, and I know AVX can be fully disabled using the existing masks, so perhaps this is not necessary and there is something I'm missing?

**Comment by loganwendholt** [comment]
Spent some more time trying to debug this. Made a few observations:
- Whatever is causing this PKRU data to be saved in XSTATE, it is not consistent / deterministic. Re-running the exact same recording command in a loop, I'm only seeing this show up on maybe 1 out of every 100 recordings
- I used bpftrace to monitor the system for any `pkey_*` syscalls, and ran the above test loop until I saw the PKRU bits again. No `pkey_*` syscalls were detected. 

At this point, I'm really at a loss as to what the root cause is. 

As an alternate approach, I'm thinking about modifying `ExtraRegisters::set_to_raw_data` to use a best-effort approach if the record and replay CPU features don't match up. Something along the lines of ignoring / not copying any saved XSAVE data which is not supported by the replay machine.

Does that sound feasible?

**Comment by khuey** [comment]
What CPU and kernel do you have?

**Comment by loganwendholt** [comment]
I'm using kernel version 5.2.9 on an Intel Xeon Skylake processor.

**Comment by rocallahan** [comment]
When you see PKRU being set in the XSAVE state, what is it set to?

**Comment by loganwendholt** [comment]
When it happens, it is always set to `0x54555555`.

**Comment by rocallahan** [comment]
> You might want to instrument rr so that in every RecordTask::did_wait, call into ExtraRegisters to check if the PKRU feature is in use.

Did you do this? If so, when does this rogue PKRU value first show up in trace? E.g. is it at the start, or does it pop up during the trace?

**Comment by loganwendholt** [comment]
I added logging to the `features_used` function that I linked above, but haven't instrumented RecordTask::did_wait yet. I'll do that first thing in the morning (US Eastern). 

Based on the logging that I've already added, I typically see a few hits on the `features_used` function without the PKRU value before I get the first log message indicating that it has been set, so I think it's safe to say that it pops up during the trace rather than showing up from the start.

**Comment by rocallahan** [comment]
It would be very interesting to know if this is always associated with some point in the trace or whether it pops up essentially randomly.

It might helpful to instrument the kernel with printk at all the places you can find that set PKRU.

Other than the pkey syscalls, I think PKRU may be used to implement exec-only memory. See https://pow.gs/mirror/linux/commit/62b5f7d013fc455b8db26cf01e421f4c0d264b92 for example. Given you can only reproduce this rarely, that probably isn't the problem here, but who knows...

**Comment by rocallahan** [comment]
One wild possibility, for example, is that there is some process that uses exec-only memory, and for some reason Linux is optimizing things so that the PRKU is not saved/restored fully across context switches in some don't-care cases, and you hit this bug when context switching puts that process and the rr tracee on the same core.

It might be helpful to look at kernel traces to see if these PKRU states are associated with context switches.

**Comment by loganwendholt** [comment]
Looking into the logging a bit more closely, I'm wondering if instrumenting `did_wait` will actually provide any additional information over logging within the `features_used` function. `features_used` is being called from within `ExtraRegisters::set_to_raw_data`, which seems to be involved every time the extended register data is updated. 

Perhaps the alternative is to read the register directly (rather than looking at the XSAVE data) using something like `xsave_register_data()`? I'm not too familiar with this part of the code, but it looks like I would need to add support for the PKRU register?

**Comment by rocallahan** [comment]
> ExtraRegisters::set_to_raw_data, which seems to be involved every time the extended register data is updated.

It isn't. During recording we fetch those registers via `Task::extra_regs()` which does not call `set_to_raw_data()`. Also, we normally don't fetch those registers on every event. Thus I suggest calling `extra_regs()` within `RecordTask::did_wait()`.

It certainly would be more efficient to read PKRU directly if there's a way to do that via ptrace, but I'm not sure there is, and anyway, this is just temporary code for debugging so efficiency doesn't matter; using existing `ExtraRegisters` code is going to be easier.

**Comment by loganwendholt** [comment]
> Other than the pkey syscalls, I think PKRU may be used to implement exec-only memory. See  https://pow.gs/mirror/linux/commit/62b5f7d013fc455b8db26cf01e421f4c0d264b92 for example. Given you can only reproduce this rarely, that probably isn't the problem here, but who knows...

In this commit message, I noticed the following passage:
> If a user calls:
>
>	mmap(..., PROT_EXEC);
>or
>	mprotect(ptr, sz, PROT_EXEC);
>
>(note PROT_EXEC-only without PROT_READ/WRITE), the kernel will
notice this, and set a special protection key on the memory.  It
also sets the appropriate bits in the Protection Keys User Rights
(PKRU) register so that the memory becomes unreadable and
unwritable.

So I used bpftrace to look for these calls:

```
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_mmap /args->prot == 0x4/ { @ [comm] = count(); }'

sudo bpftrace -e 'tracepoint:syscalls:sys_enter_mprotect /args->prot == 0x4/ { @ [comm] = count(); }'
```
and stress-tested the recordings again until the PKRU data showed up again. Sadly, no luck -- bpftrace didn't pick up any matching syscalls.

**Comment by loganwendholt** [comment]
Okay, I think I've got some log data worth looking at.

I added some extra logging to `did_wait()`:

``` c++
void RecordTask::did_wait() {
    auto regs = this->extra_regs();
    uint64_t features;
    memcpy(&features, regs.data_bytes() + 512, sizeof(features));
    LOG(debug) << "did_wait features: " << HEX(features);

```

Based on this, it looks like the PKRU feature bit is set by the first time the logging is triggered:

```
  11 [INFO record()] Start recording...
  12 [util] CPUID faulting works
  13 [PerfCounters] has_ioc_period_bug=0
  14 [PerfCounters_x86] supports txcp=1
  15 [PerfCounters_x86] has_kvm_in_txcp_bug=0 count=1301
  16 [PerfCounters] only_one_counter=0
  17 [Session] Session 0x94f290 created
  18 [ThreadGroup] creating new thread group 2636286
  19 [HasTaskSet] adding 2636286 to task set 0x94efe0
  20 [HasTaskSet] adding 2636286 to task set 0x953270
  21 [HasTaskSet] adding 2636286 to task set 0x953640
  22 [Task] going into blocking waitid(2636286) ...
  23 [Task]   Task 2636286 changed status to 0x137f (STOP-SIGSTOP)
  24 [Task]   (refreshing register cache)
  25 [Task] Requesting registers from tracee 2636286
  26 [Task]   (refreshing extra-register cache using XSAVE)
  27 [RecordTask] did_wait features: 0x203
  28 [Scheduler] Scheduling next task (PREVENT_SWITCH)
  29 [Scheduler]   need to reschedule
  30 [Scheduler] Task event is (none)
```

Then after the first `exec`, the feature bits change first to `0x200`, then to `0x01`:

```
 391 [RecordSession]   traced syscall entered: execve
 392 [RecordSession] EXEC_SYSCALL_ENTRY: status=0x7057f (PTRACE_EVENT_SECCOMP)
 393 [RecordTask] Wrote event SYSCALL: execve for time 13
 394 [RecordSession] after cont: status=0x7057f (PTRACE_EVENT_SECCOMP)
 395 [RecordSession] EXEC_START: status=0x7057f (PTRACE_EVENT_SECCOMP)
 396 [Task] resuming execution of 2636286 with PTRACE_SYSCALL tick_period -2 wait 1
 397 [Task] Flushing registers for tid 2636286 { args:(0x7ffea4fe54d0,0x94f850,0x950d80,0x9,0x7fd058211220,140731666552000) orig_syscall: 59 syscallno: -38 }
 398 [Scheduler] Scheduling next task (ALLOW_SWITCH)
 399 [Scheduler]   all tasks blocked, waiting for runnable (1 total)
 400 [Scheduler]   2636286 changed status to 0x4057f (PTRACE_EVENT_EXEC)
 401 [Task]   Task 2636286 changed status to 0x4057f (PTRACE_EVENT_EXEC)
 402 [Task]   (refreshing register cache)
 403 [Task] Requesting registers from tracee 2636286
 404 [Task]   (refreshing extra-register cache using XSAVE)
 405 [RecordTask] did_wait features: 0x200
 406 [RecordSession] trace time 14: Active task is 2636286. Events:
 407 [INFO log()] SYSCALL: execve
 408 [INFO log()] (none)

…

458 [HasTaskSet] adding 2636286 to task set 0x954df0
 459 [HasTaskSet] adding 2636286 to task set 0x94ab10
 460 [RecordSession] EXEC_START: status=0x4057f (PTRACE_EVENT_EXEC)
 461 [Task] resuming execution of 2636286 with PTRACE_SYSCALL tick_period -2 wait 1
 462 [Scheduler] Scheduling next task (PREVENT_SWITCH)
 463 [Scheduler]   (2636286 is un-switchable at SYSCALL: execve)
 464 [Scheduler]   and running; waiting for state change
 465 [Scheduler] Using unlimited ticks mode
 466 [Task]   Task 2636286 changed status to 0x857f (SYSCALL)
 467 [Task]   (refreshing register cache)
 468 [Task] Requesting registers from tracee 2636286
 469 [Task]   (refreshing extra-register cache using XSAVE)
 470 [RecordTask] did_wait features: 0x1
 471 [Scheduler]   new status is 0x857f (SYSCALL)
 472 [RecordSession] trace time 14: Active task is 2636286. Events:
 473 [INFO log()] SYSCALL: execve
 474 [INFO log()] (none)
 475 [RecordSession] EXEC_IN_SYSCALL: status=0x857f (SYSCALL)
```

Under a "normal" recording, the PKRU feature bit is never set again. However, on a "bad" recording, it shows up again much later:

```
 92483 [RecordSession] EXEC_SYSCALL_ENTRY: status=0x7057f (PTRACE_EVENT_SECCOMP)
 92484 [RecordTask] Wrote event SYSCALL: rt_sigaction for time 3521
 92485 [RecordSession] after cont: status=0x7057f (PTRACE_EVENT_SECCOMP)
 92486 [RecordSession] EXEC_START: status=0x7057f (PTRACE_EVENT_SECCOMP)
 92487 [Task] resuming execution of 2725682 with PTRACE_SYSCALL tick_period -2 wait 1
 92488 [Task] Flushing registers for tid 2725682 { args:(0x3,0x7ffdb6a9cd30,0x7ffdb6a9cdd0,0x8,0x7ffdb6a9cf20,140727668035024) orig_syscall: 13 syscallno: -38 }
 92489 [Scheduler] Scheduling next task (PREVENT_SWITCH)
 92490 [Scheduler]   (2725682 is un-switchable at SYSCALL: rt_sigaction)
 92491 [Scheduler]   and running; waiting for state change
 92492 [Task] going into blocking waitid(2725682) ...
 92493 [Task]   Task 2725682 changed status to 0x857f (SYSCALL)
 92494 [Task]   (refreshing register cache)
 92495 [Task] Requesting registers from tracee 2725682
 92496 [Task]   (refreshing extra-register cache using XSAVE)
 92497 [RecordTask] did_wait features: 0x3
 92498 [Scheduler]   new status is 0x857f (SYSCALL)
 92499 [RecordSession] trace time 3522: Active task is 2725682. Events:
 92500 [INFO log()] SYSCALL: rt_sigaction
 92501 [INFO log()] (none)
 92502 [RecordSession] EXEC_IN_SYSCALL: status=0x857f (SYSCALL)
 92503 [Scheduler] Scheduling next task (PREVENT_SWITCH)
 92504 [Scheduler]   (2725682 is un-switchable at SYSCALL: rt_sigaction)
 92505 [RecordSession] trace time 3522: Active task is 2725682. Events:
 92506 [INFO log()] SYSCALL: rt_sigaction
 92507 [INFO log()] (none)
 92508 [RecordSession] EXEC_SYSCALL_DONE: status=0x857f (SYSCALL)
 92509 [RecordSession]   original_syscallno:13 (rt_sigaction); return val:0
 92510 [record_syscall] 2725682: processing: SYSCALL: rt_sigaction -- time: 3522
 92511 [RecordTask] Wrote event SYSCALL: rt_sigaction for time 3522
 92512 [Scheduler] Scheduling next task (ALLOW_SWITCH)
 92513 [Scheduler] Task event is (none)
 92514 [Scheduler]   2725682 isn't blocked
 92515 [Scheduler]   Carrying on with task 2725682
 92516 [RecordSession] trace time 3523: Active task is 2725682. Events:
 92517 [INFO log_pending_events()] (no pending events)
 92518 [RecordSession] EXEC_START: status=0x857f (SYSCALL)
 92519 [PerfCounters] Resetting counters with period 1369619
 92520 [Task] resuming execution of 2725682 with PTRACE_CONT tick_period 1369619 wait 1
 92521 [Task] Flushing registers for tid 2725682 { args:(0x3,0x7ffdb6a9cd30,0x7ffdb6a9cdd0,0x8,0x7ffdb6a9cf20,140727668035024) orig_syscall: 13 syscallno: 0 }
 92522 [Scheduler] Scheduling next task (PREVENT_SWITCH)
 92523 [Scheduler]   (2725682 is un-switchable at (none))
 92524 [Scheduler]   and running; waiting for state change
 92525 [Task] going into blocking waitid(2725682) ...
 92526 [Task]   Task 2725682 changed status to 0x7057f (PTRACE_EVENT_SECCOMP)
 92527 [Task]   (refreshing register cache)
 92528 [Task] Requesting registers from tracee 2725682
 92529 [Task]   (refreshing extra-register cache using XSAVE)
 92530 [RecordTask] did_wait features: 0x203
 92531 [Scheduler]   new status is 0x7057f (PTRACE_EVENT_SECCOMP)
 92532 [RecordSession] trace time 3523: Active task is 2725682. Events:
 92533 [INFO log_pending_events()] (no pending events)
 92534 [RecordSession]   2725682: handle_ptrace_event PTRACE_EVENT_SECCOMP: event (none)
```

The trace from a "good" recording looks exactly the same up to this point, except the final `did_wait features` contains `0x3` rather than `0x203`.

**Comment by rocallahan** [comment]
Thanks for that. This looks bad.

I'd still very much like to know why the PKRU state is flipping on and off. It could well be a kernel bug and that should be fixed. But I understand it could be a lot of work to figure that out. If you feel up to it, then I do recommend monitoring kernel CPU scheduling to see if PKRU flipping correlates with context switches to other processes on that core ... and, if all else fails, printk() instrumentation of the kernel.

**Comment by loganwendholt** [comment]
Still trying to figure this out.

I've got a small program which I can use to reliably reproduce this issue:

```c
#include <stdio.h>

int main() {
    unsigned long long int i = 0;
    while(1) {
        printf("%ull\n", i);
        ++i;
    }
    return 0;
}
```

The `did_wait` logging will initially report `0x3` for a while, then some arbitrary number of passes through the loop later (takes a few mins on my machine) it switches to `0x203`. 

I tried writing up a simple ptrace program to see if I could replicate without the use of rr, but I get a consistent `0x202` from the beginning of the run using that method.

**Comment by loganwendholt** [comment]
I've been monitoring the context switches of the tracee process with `grep ctxt /proc/$pid/status`. While playing with adding a `usleep()` call inside the loop in the above code snippet, I've found that there definitely seems to be some correlation between involuntary context switches and observing the switch to `0x203`. 

If I set the sleep value high enough so that no involuntary context switches are observed, I haven't seen the `0x203` value show up at all. However, if I lower the sleep period to the point where involuntary switches do show up, I tend to see the `0x203` switch sometime shortly after.

Voluntary context switches don't seem to have any impact.

**Comment by loganwendholt** [comment]
After refining the above code snippet a bit, I can now reliably induce this error within seconds of starting a recording, using the following code:
```c
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <time.h>

int main() {
    int pid = getpid();
    printf("%d\n", pid);
    sleep(10);
    struct timespec tms;
    while(1) {
        for(long int i = 0; i < 1000000000; i++);
        clock_gettime(CLOCK_REALTIME,&tms);
        printf("%ld.%ld\n", tms.tv_sec, tms.tv_nsec);
        sleep(1);
    }
    return 0;
}
```

The important part is adding the massive busy-wait loop, which induces involuntary context switches.

**Comment by khuey** [comment]
Ok, and I assume you still don't see any pkru syscalls on the system (e.g. by monitoring the `syscalls:sys_enter_pkey_alloc` perf event)?

**Comment by loganwendholt** [comment]
Correct, there are no PKRU syscalls.

**Comment by loganwendholt** [comment]
I took a shot at putting together a quick-and-dirty reproducer that doesn't rely on rr:

```c
#include <sys/ptrace.h>
#include <sys/reg.h>
#include <sys/types.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <unistd.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <linux/elf.h>
#include <string.h>
#include <sys/uio.h>
#include <errno.h>

int main(int argc, char *argv[]) {

    if(argc != 2) {
        printf("Usage: reproducer <program>\n");
        return -1;
    }

    pid_t child = fork();
    if(child == 0) {
        char *args[] = {NULL, NULL};

        ptrace(PTRACE_TRACEME, 0, 0, 0);

        args[0] = argv[1];
        execve(args[0], args, NULL);
    }
    else {
        uint8_t data[8192];
        struct iovec vec;
        vec.iov_base = data;
        vec.iov_len = sizeof(data);
        uint32_t features;

        bool init = false;

        waitpid(child, 0, 0);

        while(1) {
            ptrace(PTRACE_SYSCALL, child, 0, 0);
            if (waitpid(child, 0, 0) == -1) {
                printf("%s\n", strerror(errno));
                return -1;
            }

            // Reset XSTATE registers
            if (!init) {
                uint32_t DREG_64_MXCSR = 0x1f80;
                uint32_t DREG_64_FCTRL = 0x37f;
                uint64_t xinuse;

                ptrace(PTRACE_GETREGSET, child, NT_X86_XSTATE, &vec);
                memset(vec.iov_base, 0, vec.iov_len);
                memcpy(vec.iov_base + 24, &DREG_64_MXCSR, 4);
                memcpy(vec.iov_base, &DREG_64_FCTRL, 4);
                memcpy(&xinuse, vec.iov_base + 512, sizeof(xinuse));
                xinuse |= 1;
                memcpy(vec.iov_base + 512, &xinuse, sizeof(xinuse));
                ptrace(PTRACE_SETREGSET, child, NT_X86_XSTATE, &vec);

                init = true;
            }

            // Get syscall
            struct user_regs_struct regs;
            if (ptrace(PTRACE_GETREGS, child, 0, &regs) == -1) {
                printf("%s\n", strerror(errno));
                return -1;
            }
            long syscall = regs.orig_rax;
            printf("syscall: %ld\n", syscall);

            // Get XSTATE registers
            ptrace(PTRACE_GETREGSET, child, NT_X86_XSTATE, &vec);
            memcpy(&features, vec.iov_base + 512, sizeof(features));
            printf("XSAVE feature mask: 0x%x\n", features);
        }
    }
    return 0;
}
```

The strange thing is, even after resetting the registers the same way `ExtraRegisters::reset()` does, I see the `0x203` value show up almost right away, with no need to induce an involuntary context switch:

```
./reproducer /usr/bin/uname                                                                                                                                                                   [81/477419]
syscall: 12
XSAVE feature mask: 0x1
syscall: 12
XSAVE feature mask: 0x1
syscall: 9
XSAVE feature mask: 0x1
syscall: 9
XSAVE feature mask: 0x1
syscall: 21
XSAVE feature mask: 0x201
syscall: 21
XSAVE feature mask: 0x201
syscall: 2

...

syscall: 10
XSAVE feature mask: 0x201
syscall: 10
XSAVE feature mask: 0x201
syscall: 9
XSAVE feature mask: 0x201

...

XSAVE feature mask: 0x201
syscall: 10
XSAVE feature mask: 0x201
syscall: 10
XSAVE feature mask: 0x201
syscall: 11
XSAVE feature mask: 0x201
syscall: 11
XSAVE feature mask: 0x201
syscall: 12
XSAVE feature mask: 0x203
syscall: 12
XSAVE feature mask: 0x203
syscall: 12
XSAVE feature mask: 0x203
```

I have no idea what to make of that.

**Comment by rocallahan** [comment]
You might want to log the actual PKRU value in your reproducer.

Then it seems like kernel debugging might be required.

**Comment by loganwendholt** [comment]
I believe I've got a fix for this problem in #2651.

From what I can tell, the underlying kernel behavior doesn't appear to be a bug. It appears to be the result of aggressive optimization in which the PKRU register isn't fully updated by XSAVE if the PKRU feature bit isn't set in the XSAVE header. This seems to make sense; if the feature is disabled, the register contents are essentially treated as "don't care".

By setting the PKRU feature bit during reset, we can ensure that the value we set the register to after reset (`0x0`) is handled properly by the kernel and is properly restored after an involuntary context switch.

On replay, this `0x0` PKRU value is detected and the PKRU feature bit is ignored (due to PKRU not actually being used), which ensures that the trace should be portable.

Based on my testing, the modifications in the above PR solve all issues I've reported in this thread.

**Comment by loganwendholt** [comment]
Now that the above PR is merged, this should be resolved. Thanks for the assistance on talking through this one!

**Comment by andronat** [comment]
Hello everyone! We recently detected that replaying from a Skylake processor to a Broadwell is broken with the following error:

```
[ERROR third-party/rr/src/ExtraRegisters.cc:557:set_to_raw_data()] Feature 9 has wrong size 8, expected 0
[FATAL third-party/rr/src/TraceStream.cc:592:read_frame()] Invalid extended register data in trace
```

After some debugging I found that the problem is this specific line [here](https://github.com/rr-debugger/rr/commit/25a6578c8e704ad6b58eac3b213f9fa8a20c1d9f#diff-df077e376f403a72a3cec7ab96035518d8fd9c3a84682f5ae52363875d1a5ec6R666).

Given the discussion here, my understanding is that we can't assume that the default value `0x55555554` is there if PKRU is not set? Please correct me if i'm wrong as my understanding of this subject is quite limited.

Nevertheless, commenting out the line above, makes our traces portable across the 2 CPUs.
